version: '3.7'

volumes:
    logs:
        driver: local
    mariadb:
        driver: local

services:
    slim:
        image: php:8.2-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        depends_on:
            - mariadb
        links:
            - mariadb
        environment:
            docker: "true"
        ports:
            - "8080:8080/tcp"
        volumes:
            - .:/var/www
            - logs:/var/www/logs

    mariadb:
        image: mariadb:10
        restart: unless-stopped
        ports:
            - "3306:3306/tcp"
        volumes:
            - mariadb:/var/lib/mysql
            - ./parkman.sql:/docker-entrypoint-initdb.d/parkman.sql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: parkman
            MYSQL_USER: parkman
            MYSQL_PASSWORD: parkman
